apiVersion: v1

kind: Service

metadata:

  name: nodeapp-service

spec:

  selector:

      app: nodeapp

    type: Loadbalancer

        app: nginx


        ports:
        
        - protocol: TCP
          port: 5000 
          targetport: 3000
        - nodePort: 3000